name: news_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
     - assets/fonts/
     - assets/icons/
     - assets/images/

  fonts:
     - family: Exo
       fonts:
         - asset: assets/fonts/Exo-Bold.ttf
         - asset: assets/fonts/Exo-Medium.ttf
         - asset: assets/fonts/Exo-Regular.ttf
         - asset: assets/fonts/Exo-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
